/* Effettivo_logico: */
DROP DATABASE IF EXISTS Effettivo;
CREATE DATABASE Effettivo;
USE Effettivo;

DROP TABLE IF EXISTS Pessoa CASCADE;
CREATE TABLE Pessoa (
    CODG_PESSOA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESC_NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE,
    CODG_CARGO INT
);

DROP TABLE IF EXISTS Cargo CASCADE;
CREATE TABLE Cargo (
    CODG_CARGO INT PRIMARY KEY NOT NULL,
    DESC_CARGO VARCHAR(255) NOT NULL
);
 
ALTER TABLE Pessoa ADD CONSTRAINT FK_Pessoa_2
    FOREIGN KEY (CODG_CARGO)
    REFERENCES Cargo (CODG_CARGO)
    ON DELETE SET NULL;
